# Generated by Django 2.1.7 on 2019-02-27 22:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import athena.works.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [("authentication", "0001_initial"), ("edu", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=254)),
                (
                    "document",
                    models.FileField(
                        null=True,
                        storage=athena.works.storage.OverwriteStorage(),
                        upload_to=athena.works.storage.upload_report,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        null=True,
                        storage=athena.works.storage.OverwriteStorage(),
                        upload_to=athena.works.storage.upload_report,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["zip"]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Accepted"), ("F", "To fix"), ("N", "Not done")],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("checked", models.DateTimeField(null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="authentication.Student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=254)),
                (
                    "templates",
                    models.FileField(
                        null=True,
                        storage=athena.works.storage.OverwriteStorage(),
                        upload_to=athena.works.storage.upload_task,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["zip"]
                            )
                        ],
                    ),
                ),
                ("deadline", models.DateTimeField()),
                (
                    "groups",
                    models.ManyToManyField(related_name="task", to="edu.StudentGroup"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="edu.Subject"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="works.Task"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="task", unique_together={("subject", "theme")}
        ),
        migrations.AlterUniqueTogether(
            name="report", unique_together={("task", "student")}
        ),
    ]
