# Generated by Django 2.1.7 on 2019-04-07 11:18

import athena.core.storage
import athena.works.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0002_auto_20190406_2037"),
        ("authentication", "0001_initial"),
        ("works", "0002_auto_20190406_2037"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report", old_name="checked", new_name="check_datetime"
        ),
        migrations.RenameField(
            model_name="report", old_name="created_datetime", new_name="create_datetime"
        ),
        migrations.RenameField(
            model_name="report", old_name="document", new_name="file"
        ),
        migrations.RenameField(model_name="report", old_name="title", new_name="name"),
        migrations.RenameField(
            model_name="task", old_name="templates", new_name="attachment"
        ),
        migrations.RenameField(
            model_name="task", old_name="created_datetime", new_name="create_datetime"
        ),
        migrations.RenameField(model_name="task", old_name="theme", new_name="name"),
        migrations.AddField(
            model_name="report",
            name="comment",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="report",
            name="edit_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="authentication.Teacher",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="tutor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="authentication.Tutor",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="edit_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(
                null=True,
                storage=athena.core.storage.OverwriteStorage(),
                upload_to=athena.works.models.report_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="student_group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="edu.StudentGroup",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="report",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="works.Task",
            ),
        ),
        migrations.AlterField(
            model_name="task", name="deadline", field=models.DateTimeField(null=True)
        ),
        migrations.RemoveField(model_name="task", name="groups"),
        migrations.AlterUniqueTogether(
            name="task", unique_together={("name", "subject", "student_group")}
        ),
    ]
