# Generated by Django 2.1.7 on 2019-03-31 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('works', '0002_auto_20190329_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks',
                                    to='edu.Subject'),
        ),
    ]
