# Generated by Django 2.2 on 2019-04-16 00:14

import django.core.validators
from django.db import migrations, models

import athena.core.storage
import athena.works.models


class Migration(migrations.Migration):
    dependencies = [
        ('works', '0003_auto_20190407_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.FileField(max_length=255, null=True, storage=athena.core.storage.OverwriteStorage(),
                                   upload_to=athena.works.models.report_upload_to, validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(max_length=255, null=True, storage=athena.core.storage.OverwriteStorage(),
                                   upload_to=athena.works.models.report_upload_to, validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(max_length=255, null=True, storage=athena.core.storage.OverwriteStorage(),
                                   upload_to=athena.works.models.task_upload_to, validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(max_length=255, null=True, storage=athena.core.storage.OverwriteStorage(),
                                   upload_to=athena.works.models.report_upload_to, validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
