# Generated by Django 2.1.5 on 2019-02-08 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='subject_id',
        ),
    ]
