# Generated by Django 2.1.5 on 2019-02-08 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('edu', '0002_remove_studentgroup_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
