# Generated by Django 2.1.5 on 2019-02-09 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('edu', '0003_auto_20190209_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
