# Generated by Django 2.1.5 on 2019-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("edu", "0004_auto_20190209_1117")]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.SmallIntegerField(default=1),
        )
    ]
