# Generated by Django 2.1.5 on 2019-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("edu", "0005_subject_semester")]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="subject", unique_together={("name", "semester")}
        ),
    ]
