# Generated by Django 2.1.5 on 2019-02-09 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0002_student_teacher_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='student_group',
        ),
    ]
