# Generated by Django 2.1.7 on 2019-03-17 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='student',
            name='cipher',
            field=models.CharField(default=None, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62873f25-ab1e-5493-88d4-8f54fa1cd98a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62873f25-ab1e-5493-88d4-8f54fa1cd98a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62873f25-ab1e-5493-88d4-8f54fa1cd98a'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
