# Generated by Django 2.2 on 2019-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("authentication", "0007_auto_20190427_2006")]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="teachers",
            field=models.ManyToManyField(
                related_name="tutors", to="authentication.Teacher"
            ),
        )
    ]
