# Generated by Django 2.1.7 on 2019-03-17 21:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("62873f25-ab1e-5493-88d4-8f54fa1cd98a"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("quantity", models.PositiveSmallIntegerField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("62873f25-ab1e-5493-88d4-8f54fa1cd98a"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("semester", models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="subject", unique_together={("name", "semester")}
        ),
    ]
