# Generated by Django 2.1.7 on 2019-03-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('edu', '0002_auto_20190329_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
