# Generated by Django 2.2 on 2019-04-21 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("edu", "0003_speciality_cipher")]

    operations = [migrations.RemoveField(model_name="studentgroup", name="quantity")]
