# Generated by Django 2.2 on 2019-05-06 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("edu", "0004_remove_studentgroup_quantity")]

    operations = [
        migrations.AddField(
            model_name="speciality",
            name="speciality",
            field=models.ManyToManyField(related_name="specialities", to="edu.Subject"),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="cipher",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator("[\\d{2}.\\d{2}}.\\d{2}")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="name",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator("[А-Яа-я]{4,6}-\\d{2}-\\d{2}")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="semester",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.RegexValidator("[1-8]{1}")],
            ),
        ),
    ]
