# Generated by Django 2.2 on 2019-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('edu', '0005_auto_20190507_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='speciality',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='speciality',
            name='cipher',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
