# Generated by Django 2.1.5 on 2019-02-08 21:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import works.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('edu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('document', models.FileField(null=True, storage=works.storage.OverwriteStorage(),
                                              upload_to=works.storage.upload_report, validators=[
                        django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('attachment', models.FileField(null=True, storage=works.storage.OverwriteStorage(),
                                                upload_to=works.storage.upload_report, validators=[
                        django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('status',
                 models.CharField(choices=[('A', 'Accepted'), ('F', 'To fix'), ('N', 'Not done')], default='N',
                                  max_length=1)),
                ('checked', models.DateTimeField(null=True)),
                ('student_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=254)),
                ('templates', models.FileField(null=True, storage=works.storage.OverwriteStorage(),
                                               upload_to=works.storage.upload_task, validators=[
                        django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('deadline', models.DateTimeField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task',
                                               to='edu.StudentGroup')),
                ('subject_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Task'),
        ),
    ]
