# Generated by Django 2.1.5 on 2019-02-09 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('works', '0002_auto_20190209_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='group_id',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Student'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Subject'),
        ),
    ]
